name: Build Docker image and push

on:
  workflow_dispatch:

jobs:
  Build_Model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Clean and preprocess the raw housing dataset
        working_directory: ./
        run: |
          python src/data/run_processing.py \
          --input data/raw/house_data.csv \
          --output data/processed/cleaned_house_data.csv

      - name: Apply transformations and generate features
        run: |
          python src/features/engineer.py \
          --input data/processed/cleaned_house_data.csv \
          --output data/processed/featured_house_data.csv \
          --preprocessor models/trained/preprocessor.pkl

      - name: Train your model and log everything to MLflow
        run: |
          python src/models/train_model.py \
          --config configs/model_config.yaml \
          --data data/processed/featured_house_data.csv \
          --models-dir models

          
  build-vote:
    needs: Build_Model
    uses: ShoryaDubey/vote/.github/workflows/docker-testing.yml@main
    with:
      service-path: ./src/api
      image-name: house_price_prediction_model
      version-tag: 1.0.0
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  build-model:
    needs: Build_Model
    uses: ShoryaDubey/vote/.github/workflows/docker-testing.yml@main
    with:
      service-path: ./streamlit_app
      image-name: house_price_prediction_web_app
      version-tag: 1.0.0
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
